name: tree_view_with_drag_and_drop
description: A customizable Flutter tree view widget with drag-and-drop support for reordering nodes. Supports generic data types and provides extensive customization options.
version: 1.0.0
homepage: https://github.com/ashish030298/tree_view_with_drag_and_drop
repository: https://github.com/ashish030298/tree_view_with_drag_and_drop
issue_tracker: https://github.com/ashish030298/tree_view_with_drag_and_drop/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


topics:
  - tree-view
  - drag-and-drop
  - hierarchical-data
  - ui
  - widget  